spring:
  datasource:
    url: jdbc:h2:mem:jpaTest
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

  jpa:
    properties:
       hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: true